# Generated by Django 3.2.4 on 2024-01-07 06:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idEstado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelosTinaco',
            fields=[
                ('idModelos_tinaco', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
                ('Descripcion', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('idModulo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TamañoTinaco',
            fields=[
                ('idTamaño_tinaco', models.IntegerField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tinaco',
            fields=[
                ('Folio', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=250)),
                ('Ape_paterno', models.CharField(max_length=250)),
                ('Ape_materno', models.CharField(max_length=250)),
                ('Correo', models.CharField(max_length=45, unique=True)),
                ('Contraseña', models.CharField(max_length=45)),
                ('fecha_de_compras', models.DateField()),
                ('registro_apertura', models.IntegerField()),
                ('acceso_de_keypad', models.IntegerField()),
                ('acceso_de_tarjeta', models.IntegerField()),
                ('duracion_apertura', models.IntegerField()),
                ('intentos_erroneos', models.IntegerField()),
                ('alarma_activacion', models.IntegerField()),
                ('Estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estado')),
                ('Modelos_tinaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modelostinaco')),
            ],
        ),
        migrations.CreateModel(
            name='STemperatura',
            fields=[
                ('Fecha_y_Hora', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('datos_sensor', models.FloatField(null=True)),
                ('Modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modulo')),
                ('Tinaco_Folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tinaco')),
            ],
        ),
        migrations.CreateModel(
            name='SSharp',
            fields=[
                ('Fecha_y_Hora', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('datos_sensor', models.FloatField(null=True)),
                ('Modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modulo')),
                ('Tinaco_Folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tinaco')),
            ],
        ),
        migrations.CreateModel(
            name='SServo',
            fields=[
                ('Fecha_y_Hora', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('datos_sensor', models.FloatField(null=True)),
                ('Modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modulo')),
                ('Tinaco_Folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tinaco')),
            ],
        ),
        migrations.CreateModel(
            name='SPh',
            fields=[
                ('Fecha_y_Hora', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('datos_sensor', models.FloatField(null=True)),
                ('Modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modulo')),
                ('Tinaco_Folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tinaco')),
            ],
        ),
        migrations.CreateModel(
            name='SNivelDeAgua',
            fields=[
                ('Fecha_y_Hora', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('datos_sensor', models.CharField(max_length=45, null=True)),
                ('Modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modulo')),
                ('Tinaco_Folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tinaco')),
            ],
        ),
        migrations.AddField(
            model_name='modelostinaco',
            name='Tamaño_tinaco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tamañotinaco'),
        ),
        migrations.CreateModel(
            name='FueraDeRango',
            fields=[
                ('Fecha_y_Hora', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('datos_sensor', models.FloatField(null=True)),
                ('TipoSensor', models.CharField(max_length=45)),
                ('Modulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.modulo')),
                ('Tinaco_Folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tinaco')),
            ],
            options={
                'unique_together': {('Fecha_y_Hora', 'datos_sensor', 'Tinaco_Folio')},
            },
        ),
    ]
