# Generated by Django 3.2.4 on 2024-01-07 14:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelosTinaco',
            fields=[
                ('idModelos_tinaco', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
                ('Descripcion', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('idModulo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TamañoTinaco',
            fields=[
                ('idTamaño_tinaco', models.IntegerField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tinaco',
            fields=[
                ('Folio', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=250)),
                ('Ape_paterno', models.CharField(max_length=250)),
                ('Ape_materno', models.CharField(max_length=250)),
                ('Correo', models.CharField(max_length=45, unique=True)),
                ('Contraseña', models.CharField(max_length=45)),
                ('fecha_de_compras', models.DateField()),
                ('registro_apertura', models.IntegerField()),
                ('acceso_de_keypad', models.IntegerField()),
                ('acceso_de_tarjeta', models.IntegerField()),
                ('duracion_apertura', models.IntegerField()),
                ('intentos_erroneos', models.IntegerField()),
                ('alarma_activacion', models.IntegerField()),
                ('Estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estado')),
                ('Modelos_tinaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modelostinaco')),
            ],
        ),
        migrations.CreateModel(
            name='STemperatura',
            fields=[
                ('idStem', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_y_Hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('datos_sensor', models.FloatField(null=True)),
                ('Modulo', models.ForeignKey(db_column='modulo_idmodulo', on_delete=django.db.models.deletion.CASCADE, to='api.modulo')),
                ('Tinaco_Folio', models.ForeignKey(db_column='tinaco_folio', on_delete=django.db.models.deletion.CASCADE, to='api.tinaco')),
            ],
            options={
                'db_table': 'stemperatura',
            },
        ),
        migrations.CreateModel(
            name='SSharp',
            fields=[
                ('idSsharp', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_y_Hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('datos_sensor', models.FloatField(null=True)),
                ('Modulo', models.ForeignKey(db_column='modulo_idmodulo', on_delete=django.db.models.deletion.CASCADE, to='api.modulo')),
                ('Tinaco_Folio', models.ForeignKey(db_column='tinaco_folio', on_delete=django.db.models.deletion.CASCADE, to='api.tinaco')),
            ],
            options={
                'db_table': 'ssharp',
            },
        ),
        migrations.CreateModel(
            name='SServo',
            fields=[
                ('idServo', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_y_Hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('datos_sensor', models.FloatField(null=True)),
                ('Modulo', models.ForeignKey(db_column='modulo_idmodulo', on_delete=django.db.models.deletion.CASCADE, to='api.modulo')),
                ('Tinaco_Folio', models.ForeignKey(db_column='tinaco_folio', on_delete=django.db.models.deletion.CASCADE, to='api.tinaco')),
            ],
            options={
                'db_table': 'sservo',
            },
        ),
        migrations.CreateModel(
            name='SPh',
            fields=[
                ('idSph', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_y_Hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('datos_sensor', models.FloatField(null=True)),
                ('Modulo', models.ForeignKey(db_column='modulo_idmodulo', on_delete=django.db.models.deletion.CASCADE, to='api.modulo')),
                ('Tinaco_Folio', models.ForeignKey(db_column='tinaco_folio', on_delete=django.db.models.deletion.CASCADE, to='api.tinaco')),
            ],
            options={
                'db_table': 'sph',
            },
        ),
        migrations.CreateModel(
            name='SNivelDeAgua',
            fields=[
                ('idSnda', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_y_Hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('datos_sensor', models.FloatField(null=True)),
                ('Modulo', models.ForeignKey(db_column='modulo_idmodulo', on_delete=django.db.models.deletion.CASCADE, to='api.modulo')),
                ('Tinaco_Folio', models.ForeignKey(db_column='tinaco_folio', on_delete=django.db.models.deletion.CASCADE, to='api.tinaco')),
            ],
            options={
                'db_table': 'sniveldeagua',
            },
        ),
        migrations.AddField(
            model_name='modelostinaco',
            name='Tamaño_tinaco_idTamaño_tinaco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tamañotinaco'),
        ),
        migrations.CreateModel(
            name='FueraDeRango',
            fields=[
                ('idFdR', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_y_Hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('datos_sensor', models.FloatField(null=True)),
                ('TipoSensor', models.CharField(max_length=45)),
                ('Modulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.modulo')),
                ('Tinaco_Folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tinaco')),
            ],
            options={
                'unique_together': {('Fecha_y_Hora', 'datos_sensor', 'Tinaco_Folio')},
            },
        ),
    ]
