# Generated by Django 3.2.4 on 2024-01-02 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fueraderango',
            name='Modulo_idModulo',
        ),
        migrations.RemoveField(
            model_name='modelostinaco',
            name='Tamaño_tinaco_idTamaño_tinaco',
        ),
        migrations.RemoveField(
            model_name='sniveldeagua',
            name='Modulo_idModulo',
        ),
        migrations.RemoveField(
            model_name='sniveldeagua',
            name='Tinaco_Folio',
        ),
        migrations.RemoveField(
            model_name='sph',
            name='Tinaco_Folio',
        ),
        migrations.RemoveField(
            model_name='sservo',
            name='Tinaco_Folio',
        ),
        migrations.RemoveField(
            model_name='ssharp',
            name='Modulo_idModulo',
        ),
        migrations.RemoveField(
            model_name='ssharp',
            name='Tinaco_Folio',
        ),
        migrations.RemoveField(
            model_name='stemperatura',
            name='Modulo_idModulo',
        ),
        migrations.RemoveField(
            model_name='stemperatura',
            name='Tinaco_Folio',
        ),
        migrations.RemoveField(
            model_name='tinaco',
            name='Estado_idEstado',
        ),
        migrations.RemoveField(
            model_name='tinaco',
            name='Modelos_tinaco_idModelos_tinaco',
        ),
        migrations.RemoveField(
            model_name='tinaco',
            name='id_usuario',
        ),
        migrations.DeleteModel(
            name='Costos',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='FueraDeRango',
        ),
        migrations.DeleteModel(
            name='ModelosTinaco',
        ),
        migrations.DeleteModel(
            name='Modulo',
        ),
        migrations.DeleteModel(
            name='SNivelDeAgua',
        ),
        migrations.DeleteModel(
            name='SPh',
        ),
        migrations.DeleteModel(
            name='SServo',
        ),
        migrations.DeleteModel(
            name='SSharp',
        ),
        migrations.DeleteModel(
            name='STemperatura',
        ),
        migrations.DeleteModel(
            name='TamañoTinaco',
        ),
        migrations.DeleteModel(
            name='Tinaco',
        ),
        migrations.DeleteModel(
            name='TipoMantenimiento',
        ),
    ]
