# Generated by Django 3.2.4 on 2024-01-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelostinaco',
            old_name='Tamaño_tinaco',
            new_name='Tamaño_tinaco_idTamaño_tinaco',
        ),
    ]
