# Generated by Django 3.2.4 on 2024-01-02 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costos',
            name='tipo_mantenimiento_idtipo_mantenimiento',
            field=models.ForeignKey(db_column='tipo_mantenimiento_idtipo_mantenimiento', on_delete=django.db.models.deletion.CASCADE, to='api.tipomantenimiento'),
        ),
    ]
