# Generated by Django 3.2.4 on 2024-01-02 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_costos_tipo_mantenimiento_idtipo_mantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelostinaco',
            name='Tamaño_tinaco_idTamaño_tinaco',
            field=models.ForeignKey(db_column='Tamaño_tinaco_idTamaño_tinaco', on_delete=django.db.models.deletion.CASCADE, to='api.tamañotinaco'),
        ),
    ]
