# Generated by Django 3.2.4 on 2024-01-02 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_modelostinaco_tamaño_tinaco_idtamaño_tinaco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sniveldeagua',
            name='Tinaco_Folio',
            field=models.ForeignKey(db_column='Tinaco_Folio', on_delete=django.db.models.deletion.CASCADE, to='api.tinaco'),
        ),
        migrations.AlterField(
            model_name='sph',
            name='Tinaco_Folio',
            field=models.ForeignKey(db_column='Tinaco_Folio', on_delete=django.db.models.deletion.CASCADE, to='api.tinaco'),
        ),
        migrations.AlterField(
            model_name='sservo',
            name='Tinaco_Folio',
            field=models.ForeignKey(db_column='Tinaco_Folio', on_delete=django.db.models.deletion.CASCADE, to='api.tinaco'),
        ),
        migrations.AlterField(
            model_name='ssharp',
            name='Tinaco_Folio',
            field=models.ForeignKey(db_column='Tinaco_Folio', on_delete=django.db.models.deletion.CASCADE, to='api.tinaco'),
        ),
        migrations.AlterField(
            model_name='stemperatura',
            name='Tinaco_Folio',
            field=models.ForeignKey(db_column='Tinaco_Folio', on_delete=django.db.models.deletion.CASCADE, to='api.tinaco'),
        ),
    ]
