# Generated by Django 3.2.4 on 2024-01-02 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20240101_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinaco',
            name='Estado_idEstado',
            field=models.ForeignKey(db_column='Estado_idEstado', on_delete=django.db.models.deletion.CASCADE, to='api.estado'),
        ),
        migrations.AlterField(
            model_name='tinaco',
            name='Modelos_tinaco_idModelos_tinaco',
            field=models.ForeignKey(db_column='Modelos_tinaco_idModelos_tinaco', on_delete=django.db.models.deletion.CASCADE, to='api.modelostinaco'),
        ),
        migrations.AlterField(
            model_name='tinaco',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
