# Generated by Django 3.2.4 on 2024-01-02 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20240101_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tinaco',
            old_name='acesso_de_tarjeta',
            new_name='acceso_de_tarjeta',
        ),
    ]
