# Generated by Django 3.2.4 on 2024-01-02 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_acesso_de_tarjeta_tinaco_acceso_de_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueraderango',
            name='Modulo_idModulo',
            field=models.ForeignKey(blank=True, db_column='Modulo_idModulo', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.modulo'),
        ),
    ]
