# Generated by Django 3.2.4 on 2024-01-02 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_fueraderango_modulo_idmodulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sniveldeagua',
            name='Modulo_idModulo',
            field=models.ForeignKey(db_column='Modulo_idModulo', on_delete=django.db.models.deletion.CASCADE, to='api.modulo'),
        ),
        migrations.AlterField(
            model_name='ssharp',
            name='Modulo_idModulo',
            field=models.ForeignKey(db_column='Modulo_idModulo', on_delete=django.db.models.deletion.CASCADE, to='api.modulo'),
        ),
        migrations.AlterField(
            model_name='stemperatura',
            name='Modulo_idModulo',
            field=models.ForeignKey(db_column='Modulo_idModulo', on_delete=django.db.models.deletion.CASCADE, to='api.modulo'),
        ),
    ]
